//Author: Jordan Bennett
import java.util.ArrayList;
import java.util.Scanner;

public class RunNeuralNetwork
{
    //features
    private static Scanner userScanner = new Scanner ( System.in );
    private static NeuralNetwork neuralNetwork = new NeuralNetwork ( );
    
    public static void main ( String [ ] stuff )
    {
        trainNeuralNetwork ( );
        testNeuralNetwork ( );
    }
    
    public static void testNeuralNetwork ( )
    {
        System.out.println ( "Neural Network Practice September 12, 2019, Jordan Bennett" );
        System.out.println ( "1. Get neural network guess on input = [1,1]" );
        System.out.println ( "2. Get neural network guess on input = [1,0]" );
        System.out.println ( "3. Get neural network guess on input = [0,1]" );
        System.out.println ( "4. Get neural network guess on input = [0,0]" );
        System.out.println ( "5. Get me out of here" );
        int userInput = userScanner.nextInt ( );
        
        switch ( userInput ) 
        {
            case 1 :
            {
                int [ ] inputs = new int [ ] { 1, 1 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess = '" + neuralNetwork.getOutcome ( ) + "' for input = [1, 1] " );                
                returnToTestMenu ( );
            } 
            break;
            
            case 2 :
            {
                int [ ] inputs = new int [ ] { 1, 0 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess = '" + neuralNetwork.getOutcome ( ) + "' for input = [1, 0] " );                
                returnToTestMenu ( );
            } 
            break;
            
            case 3 :
            {
                int [ ] inputs = new int [ ] { 0, 1 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess = '" + neuralNetwork.getOutcome ( ) + "' for input = [0, 1] " );                
                returnToTestMenu ( );
            } 
            break;
            
            case 4 :
            {
                int [ ] inputs = new int [ ] { 0, 0 };
                neuralNetwork.doForwardPropagation ( inputs );
                System.out.println ( "Neural network guess = '" + neuralNetwork.getOutcome ( ) + "' for input = [0, 0] " );                
                returnToTestMenu ( );
            } 
            break;
            
            case 5 :
            {
                System.exit ( 0 );
            }
            break;
        }
    }
    
    public static void trainNeuralNetwork ( )
    {
        ArrayList <String> trainingData = getTrainingData ( );
        
        for ( int tDI = 0; tDI < trainingData.size ( ); tDI ++ )
        {
            //forward prop
            String inputLine = trainingData.get ( tDI ).split ( ":" ) [ 0 ];
            String [ ] raw_inputs = inputLine.split ( "," );
            int [ ] inputs = new int [ ] { Integer.parseInt ( raw_inputs [ 0 ] ), Integer.parseInt ( raw_inputs [ 1 ] ) };
            neuralNetwork.doForwardPropagation ( inputs );
            
            //back prop
            int target = Integer.parseInt ( trainingData.get ( tDI ).split ( ":" ) [ 1 ] );
            neuralNetwork.doBackwardPropagation ( target );
        }
    }  
    
    public static void returnToTestMenu ( )
    {
        userScanner.nextLine ( );
        userScanner.nextLine ( );
        System.out.println ( "\f" );
        testNeuralNetwork ( );
    }
    
    public static ArrayList <String> getTrainingData ( )
    {
        ArrayList <String> returnValue = new ArrayList <String> ( );
        
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "0,1:1" );
        
        return returnValue;
    }

}
